version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 16.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane ci_ios
      - run:
          name: Fastlane
          command: bundle exec fastlane ci_macos
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
        filters:
          branches:
            only: 
              - main
              - develop