name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Set XCode version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Build and Test iOS
      - name: Build and test iOS
        run: |
          xcodebuild clean build test \
          -project iRoutes/iRoutes.xcodeproj \
          -scheme "CI_iOS" \
          -destination "platform=iOS Simulator,OS=17.4,name=iPhone 14" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES

      # Build and Test macOS
      - name: Build and test macOS
        run: |
          xcodebuild clean build test \
          -project iRoutes/iRoutes.xcodeproj \
          -scheme "CI_macOS" \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
